polyfloyd/rust-id3

src/parsers.rs

The ID3v2 spec does not mention any text encoding when describing the language bytes of the COMM/USLT frames or the format bytes of the 2.2 PIC frame.
I think this portion of the 2.4 spec indicates that ISO-8859-1 is the correct encoding to assume here:
> If nothing else is said, strings, including numeric strings and URLs  [URL], are represented as ISO-8859-1 [ISO-8859-1] characters in the range $20 - $FF.
Similarly, in the 2.2 spec, justifying the change for the PIC frame:
> If nothing else is said a string is represented as ISO-8859-1 [ISO-8859-1] characters in the range $20 - $FF.

Fixed a parsing error in COMM, PIC and USLT frames

---

src/frame/content.rs
src/lib.rs
src/parsers.rs
src/tag.rs

This change makes the getters for the `Content` enum more flexible and more like std, e.g. `Result::ok()` and `Result::err()` by using Options instead.
The library code and tests were adapted by unwrapping the returned option, mimicking the same behavior, although it would be preferable to eventually get rid of all panics. :)

frame/content: Return None instead of panicking

---

src/tag.rs

So I was playing with this library and noticed that Tag::write_to_path(file_name, version) always results in error. So I found a problem and fixed it.

use fs::OpenOptions with write flag for writing tag

---

src/stream/tag.rs

The ID3v2 specs all require the version field to be encoded as `02 00`, `03 00`, or `04 00`.

Properly encode the version field in the tag.

---

src/frame/content.rs
src/stream/frame/content.rs

I just encountered a case in my collection where the mp3 file couldn't be parsed because of a "invalid picture type". 
I don't know which program set this wrong type (it was 0xFF) but I didn't notice it before because all other programs (eg. VLC, MP3Tag, mpd, the android music player) could handle the file and its picture just fine.
So I thought that this lenient handling of `PictureType` could be appropriate here, too.
For this, I introduced the `Undefined(u8)` variant and removed the thrown parsing error.
This has the benefit that a slightly mismatched file can at least be used for the other tags.
This is a breaking change for all dependent crates which read the PictureType while trying to match all types, but as far as I can find, no one uses this. (at least in crates on crates.io and …

Be more lenient in accepting picture types

---

Cargo.toml
src/lib.rs
src/stream/tag.rs
src/tag.rs

Being used once and not using any of the advanced features, I don't think `derive_builder` pulls its weight here. This drops the release build time from 66 s to 18 s on my system, and makes things cleaner for other users (e.g. the current `derive_builder` depends on a pre-1.0 `syn`).
This is a breaking change, but we could preserve API compatibility if we wanted (the new API is nicer IMHO).

Implement Encoder builder manually

---

Cargo.toml
src/frame/timestamp.rs

This removes the `regex` dependency and further reduces release build times from 18s to 7s (on top of #34).
It's not necessarily ready because there's a behavior change: the old parser accepted any number of digits for years, and one or two for the other date parts. I should implement the same thing, because it's likely that some non-conforming files exist in the wild.

Implement a timestamp parser

---

src/v1/mod.rs

Hello
At first I was working with `v2` tags on files, using `read_from_path`. But then when I started to dig into `v1` tags, I found that the convenient `read_from_path` was missing for this version.
Therefore this PR adds it for consistency between `v1` and `v2` handling.

feat: add read_from_path function for v1 tag

---

src/error.rs

Just finished the `fmt::Display` implementation for `Error` and `ErrorKind` - so I went with your first suggestion.
I was looking over the code to see how context and messages are provided to `Error`s, to work an appropriate way to display them to users. My implementation follows these rules, when a `Error` is formatted using `fmt::Display`:
- format the `ErrorKind` using `fmt::Display`
- if the `description` field is a non-empty String, append it like this: `": example_description"`
When an `ErrorKind` is formatted, usually just the name of the kind is displayed, exceptions are:
- `ErrorKind::Io` where the IO error is formatted as well
- `ErrorKind::UnsupportedVersion` where the version is formatted as well
I chose to not format the invalid bytes for the `StringDecoding` variant, as …

Extend fmt::Display implementation for Error and add it for ErrorKind

---

Cargo.toml
src/util.rs

Removes the `encoding` crate, which hasn't been updated in 4 years.
Also makes encoding about twice as fast and decoding about 1/3 faster (I haven't done a complete benchmark, I just did a quick test to make sure I didn't make it worst).

Remove 'encoding' crate

---

src/error.rs
src/frame/timestamp.rs

Quality of tags is often bad and not all applications (or users) strictly follow the informal standards. I have experienced the situation that numbers in timestamps are padded with spaces instead of zeroes.
According to the robustness principle I suggest to simply ignore whitespace between numbers and separators. This should not cause any regressions as far as I am aware.

Ignore whitespace in timestamps

---

src/stream/frame/content.rs

I haven't been able to find much information about what GRP1 frames can contain, but as far as I can tell they're just normal `Text` frames. If I'm understanding correctly, eyed3d decodes GRP1 frames the same way.
Tested this by setting a grouping in iTunes, and that worked just fine.

Decode non-standard iTunes GRP1 frames as `Text`

---

src/frame/content.rs
src/stream/frame/content.rs
src/stream/frame/mod.rs
src/stream/frame/v2.rs
src/stream/frame/v3.rs
src/stream/frame/v4.rs
src/util.rs

This PR implements a way to correctly handle ID3v2.4 text frames. All text frames in ID3v2.4 may contain multiple values separated by null bytes, of which only the first value is returned by the current implementation.
A new test case was added to test this behaviour: `id3::stream::frame::content::tests::test_null_terminated_text_v4` tests that `text\0text\0` will be decoded to `text\0text` keeping the null byte for ID3v2.4 tags.
I have tried to keep breakage to a minimum, thus I have not added a new `Content` variant but instead opted to use the existing `Text` variant with a new function that splits the contained text into its separate values.
See also #20.

ID3v2.4 tag value splitting

---

src/stream/tag.rs
src/tag.rs

Hello, in this commit, ID3v2 version gets saved into `Tag`, and can be later retrieved using `.version()`. This is useful, if you want to read tag, and save with the same version. I also have idea changing the `write_to` functions, and make version an `Option<Version>`, however that would break the API so I didn't implement that. 
Thank you.

Save ID3v2 version

---

src/stream/tag.rs

These make the library print to stderr even in release builds

Remove dbg! prints

---

src/taglike.rs

This frame is a ID3v2.4 addition (similar to `TDRL`) which encodes Original Release Date.
I initially had a more ambitious version of this change handling upgrading from `TOR`/`TORY` frames, using logic similar to `convert_2_to_3_and_back`. However, if we stored `TOR`/`TORY` frames as `TDOR` for the in-memory representation, we would then have to ensure they get trimmed to only a year (without month, day, etc.) when encoding as a `2.3` or `2.2` tag. There is currently nowhere suitable to host this logic, so I trimmed the PR to direct manipulation of `TDOR` frames only.

Adds support for reading/writing TDOR frames

---

src/frame/timestamp.rs

This seems like a safe addition, and it would allow me to write something like this instead of enumerating the Nones: 
``` rust
tag.set_date_released(id3::Timestamp { year: 2023, ..id3::Timestamp::default() });
```
Admittedly, it would default the year to 0, not sure if this could cause practical issues somehow.

Add Default to Timestamp

---

Cargo.toml
src/stream/frame/content.rs
src/stream/tag.rs
src/tag.rs

When decoding files, picture decoding is by far the most expensive part. When running with mack[0], picture decoding alone accounts for 20% of program runtime even though the pictures are never used. No other field comes within even two orders of magnitude in terms of performance hit.
This commit adds a "decode_picture" feature, enabled by default, which allows turning off this functionality if it is not needed in order to allow increasing performance.
0: https://github.com/cdown/mack

feat: Allow disabling expensive picture decoding

---

src/frame/content.rs
src/frame/mod.rs
src/stream/frame/content.rs
src/stream/tag.rs
src/tag.rs
src/taglike.rs

Closes #99 
CTOC and CHAP frames are closely related and widely used in the world of podcasting.
Useful link:
[Reference doc](https://mutagen-specs.readthedocs.io/en/latest/id3/id3v2-chapters-1.0.html) 
[NodeJS implementation](https://github.com/Zazama/node-id3/blob/master/src/frames/frame-ctoc.ts)

feat: Added support for Table of contents frame (CTOC)

---

src/chunk.rs
src/tag.rs

The codebase defines a StorageFile trait to model anything similar to a file. By using `impl StorageFile` instead of `fs::File` in the API signatures, users are able to provide either a file or something similar (for example, `io::Cursor` to manipulate a block of data in memory).
This commit updates the APIs still using `fs::File` to `impl StorageFile`.

feat: make file-related APIs compatible with io::Cursor

---

.github/workflows/ci.yml

Assuming MSRV 1.65
Fixes #127 
Depends on fix for #126 re-based in
Failure as expected with 1.65: https://github.com/pinkforest/rust-id3/actions/runs/8002170702/job/21854841329
Where as current stable works ok.

ci: Add MSRV test

---

src/stream/frame/content.rs
src/stream/tag.rs

The spec for PrivateFrames says that a null byte should be inserted after the `owner_identifier` field.
Currently, if one adds a private frame, they will encounter read failures when decoding tags.
This PR adds the null byte to the encoder which lets tags with PrivateFrames be decoded properly.

Fix: missing null byte delimeter in PrivateFrame

---

.github/workflows/ci.yml

All feature combinations should be tested, to ensure that disabled code didn't break silently.

ci: Test all feature combinations

---

examples/tagdump.rs

I always forget how to properly dump ID3 tags to a file for testing. This tool should make it easier for other contributors.
Basically a Rust implementation of this: https://github.com/polyfloyd/rust-id3/pull/55#discussion_r568170929

chore(examples): Add tagdump helper tool

---

examples/id3info.rs

This should help when debugging issues. Fixes #81.

chore(examples): Add `id3info` example

---

src/stream/frame/content.rs
src/stream/tag.rs
src/tag.rs

Fixes #103 (at least partially - there is still no proper fix for the "AC/DC problem").
See https://github.com/polyfloyd/rust-id3/issues/103#issuecomment-2495061517 for details.

Only replace `/` in the ID3v2.2/2.3 frames mentioned in the spec

---

src/stream/frame/content.rs
src/stream/frame/v4.rs
src/stream/tag.rs

* mllt overflow
* invalid frame id length
* decode content size underflow
* decode MLLT deviation overflow
* stream tag frame bytes underflow

fix: prevent panics from malformed id3 metadata
